networks:
    net:
        name: net
        external: true  # Создается в docker-compose.db.yaml

services:
    loom-tg-bot:
        build:
            context: "../../${LOOM_TG_BOT_CONTAINER_NAME}"
            dockerfile: "${LOOM_TG_BOT_DOCKERFILE_DIR}/Dockerfile"
        container_name: "${LOOM_TG_BOT_CONTAINER_NAME}"
        env_file:
            - "../env/.env.app"
            - "../env/.env.db"
            - "../env/.env.monitoring"
        ports:
            - "${LOOM_TG_BOT_PORT}:${LOOM_TG_BOT_PORT}"
        restart: unless-stopped
        networks:
            - net

    loom-account:
        build:
            context: "../../${LOOM_ACCOUNT_CONTAINER_NAME}"
            dockerfile: "${LOOM_ACCOUNT_DOCKERFILE_DIR}/Dockerfile"
        container_name: "${LOOM_ACCOUNT_CONTAINER_NAME}"
        env_file:
            - "../env/.env.app"
            - "../env/.env.db"
            - "../env/.env.monitoring"
        ports:
            - "${LOOM_ACCOUNT_PORT}:${LOOM_ACCOUNT_PORT}"
        restart: unless-stopped
        networks:
            - net

    loom-authorization:
        build:
            context: "../../${LOOM_AUTHORIZATION_CONTAINER_NAME}"
            dockerfile: "${LOOM_AUTHORIZATION_DOCKERFILE_DIR}/Dockerfile"
        container_name: "${LOOM_AUTHORIZATION_CONTAINER_NAME}"
        env_file:
            - "../env/.env.app"
            - "../env/.env.db"
            - "../env/.env.monitoring"
        ports:
            - "${LOOM_AUTHORIZATION_PORT}:${LOOM_AUTHORIZATION_PORT}"
        restart: unless-stopped
        networks:
            - net

    loom-employee:
        build:
            context: "../../${LOOM_EMPLOYEE_CONTAINER_NAME}"
            dockerfile: "${LOOM_EMPLOYEE_DOCKERFILE_DIR}/Dockerfile"
        container_name: "${LOOM_EMPLOYEE_CONTAINER_NAME}"
        env_file:
            - "../env/.env.app"
            - "../env/.env.db"
            - "../env/.env.monitoring"
        ports:
            - "${LOOM_EMPLOYEE_PORT}:${LOOM_EMPLOYEE_PORT}"
        restart: unless-stopped
        networks:
            - net

    loom-organization:
        build:
            context: "../../${LOOM_ORGANIZATION_CONTAINER_NAME}"
            dockerfile: "${LOOM_ORGANIZATION_DOCKERFILE_DIR}/Dockerfile"
        container_name: "${LOOM_ORGANIZATION_CONTAINER_NAME}"
        env_file:
            - "../env/.env.app"
            - "../env/.env.db"
            - "../env/.env.monitoring"
        ports:
            - "${LOOM_ORGANIZATION_PORT}:${LOOM_ORGANIZATION_PORT}"
        restart: unless-stopped
        networks:
            - net

    loom-content:
        build:
            context: "../../${LOOM_CONTENT_CONTAINER_NAME}"
            dockerfile: "${LOOM_CONTENT_DOCKERFILE_DIR}/Dockerfile"
        container_name: "${LOOM_CONTENT_CONTAINER_NAME}"
        env_file:
            - "../env/.env.app"
            - "../env/.env.db"
            - "../env/.env.monitoring"
        ports:
            - "${LOOM_CONTENT_PORT}:${LOOM_CONTENT_PORT}"
        restart: unless-stopped
        networks:
            - net