x-logging: &default-logging
    driver: "json-file"
    options:
        max-size: "10m"
        max-file: "3"

networks:
    net:
        name: net
        driver: bridge

services:
    loom-tg-bot-api:
        image: aiogram/telegram-bot-api:latest
        container_name: "${LOOM_TG_BOT_API_CONTAINER_NAME}"
        restart: unless-stopped
        environment:
            TELEGRAM_API_ID: "${LOOM_TG_API_ID}"
            TELEGRAM_API_HASH: "${LOOM_TG_API_HASH}"
            TELEGRAM_LOCAL: "1"
            TELEGRAM_STAT: "1"
        volumes:
            - "../${LOOM_TG_BOT_API_VOLUME_DIR}:/var/lib/telegram-bot-api"
        ports:
            - "${LOOM_TG_BOT_API_PORT}:${LOOM_TG_BOT_API_PORT}"
            - "8082:8082"

    loom-tg-bot-postgres:
        image: postgres:17.6
        container_name: "${LOOM_TG_BOT_POSTGRES_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_TG_BOT_POSTGRES_VOLUME_DIR}:/var/lib/postgresql/data"
        ports:
            - "${LOOM_TG_BOT_POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: "${LOOM_TG_BOT_POSTGRES_DB_NAME}"
            POSTGRES_USER: "${LOOM_TG_BOT_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${LOOM_TG_BOT_POSTGRES_PASSWORD}"
            PGDATA: /var/lib/postgresql/data/pgdata
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    loom-brief-tg-bot-postgres:
        image: postgres:17.6
        container_name: "${LOOM_BRIEF_TG_BOT_POSTGRES_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_BRIEF_TG_BOT_POSTGRES_VOLUME_DIR}:/var/lib/postgresql/data"
        ports:
            - "${LOOM_BRIEF_TG_BOT_POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: "${LOOM_BRIEF_TG_BOT_POSTGRES_DB_NAME}"
            POSTGRES_USER: "${LOOM_BRIEF_TG_BOT_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${LOOM_BRIEF_TG_BOT_POSTGRES_PASSWORD}"
            PGDATA: /var/lib/postgresql/data/pgdata
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    loom-account-postgres:
        image: postgres:17.6
        container_name: "${LOOM_ACCOUNT_POSTGRES_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_ACCOUNT_POSTGRES_VOLUME_DIR}:/var/lib/postgresql/data"
        ports:
            - "${LOOM_ACCOUNT_POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: "${LOOM_ACCOUNT_POSTGRES_DB_NAME}"
            POSTGRES_USER: "${LOOM_ACCOUNT_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${LOOM_ACCOUNT_POSTGRES_PASSWORD}"
            PGDATA: /var/lib/postgresql/data/pgdata
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    loom-authorization-postgres:
        image: postgres:17.6
        container_name: "${LOOM_AUTHORIZATION_POSTGRES_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_AUTHORIZATION_POSTGRES_VOLUME_DIR}:/var/lib/postgresql/data"
        ports:
            - "${LOOM_AUTHORIZATION_POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: "${LOOM_AUTHORIZATION_POSTGRES_DB_NAME}"
            POSTGRES_USER: "${LOOM_AUTHORIZATION_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${LOOM_AUTHORIZATION_POSTGRES_PASSWORD}"
            PGDATA: /var/lib/postgresql/data/pgdata
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    loom-employee-postgres:
        image: postgres:17.6
        container_name: "${LOOM_EMPLOYEE_POSTGRES_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_EMPLOYEE_POSTGRES_VOLUME_DIR}:/var/lib/postgresql/data"
        ports:
            - "${LOOM_EMPLOYEE_POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: "${LOOM_EMPLOYEE_POSTGRES_DB_NAME}"
            POSTGRES_USER: "${LOOM_EMPLOYEE_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${LOOM_EMPLOYEE_POSTGRES_PASSWORD}"
            PGDATA: /var/lib/postgresql/data/pgdata
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    loom-organization-postgres:
        image: postgres:17.6
        container_name: "${LOOM_ORGANIZATION_POSTGRES_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_ORGANIZATION_POSTGRES_VOLUME_DIR}:/var/lib/postgresql/data"
        ports:
            - "${LOOM_ORGANIZATION_POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: "${LOOM_ORGANIZATION_POSTGRES_DB_NAME}"
            POSTGRES_USER: "${LOOM_ORGANIZATION_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${LOOM_ORGANIZATION_POSTGRES_PASSWORD}"
            PGDATA: /var/lib/postgresql/data/pgdata
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    loom-content-postgres:
        image: postgres:17.6
        container_name: "${LOOM_CONTENT_POSTGRES_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_CONTENT_POSTGRES_VOLUME_DIR}:/var/lib/postgresql/data"
        ports:
            - "${LOOM_CONTENT_POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: "${LOOM_CONTENT_POSTGRES_DB_NAME}"
            POSTGRES_USER: "${LOOM_CONTENT_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${LOOM_CONTENT_POSTGRES_PASSWORD}"
            PGDATA: /var/lib/postgresql/data/pgdata
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net


    loom-monitoring-redis:
        image: redis:8.0.2
        container_name: "${LOOM_MONITORING_REDIS_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_MONITORING_REDIS_CONFIG_FILE}:/etc/redis/redis.conf"
            - "../${LOOM_MONITORING_REDIS_VOLUME_DIR}:/data"
        ports:
            - "${LOOM_MONITORING_REDIS_PORT}:6379"
        command: "redis-server /etc/redis/redis.conf"
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    loom-loki:
        image: grafana/loki:3.5.1
        container_name: "${LOOM_LOKI_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_LOKI_CONFIG_FILE}:/etc/loki/loki.yaml:ro"
            - "../${LOOM_LOKI_VOLUME_DIR}:/loki"
        ports:
            - "${LOOM_LOKI_HTTP_PORT}:${LOOM_LOKI_HTTP_PORT}"
            - "${LOOM_LOKI_GRPC_PORT}:${LOOM_LOKI_GRPC_PORT}"
        command: [ "-config.file=/etc/loki/loki.yaml" ]
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    loom-tempo:
        image: grafana/tempo:2.7.2
        container_name: "${LOOM_TEMPO_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_TEMPO_CONFIG_FILE}:/etc/tempo/tempo.yaml:ro"
            - "../${LOOM_TEMPO_VOLUME_DIR}:/var/tempo"
        ports:
            - "${LOOM_TEMPO_HTTP_PORT}:${LOOM_TEMPO_HTTP_PORT}"
            - "${LOOM_TEMPO_GRPC_PORT}:${LOOM_TEMPO_GRPC_PORT}"
            - "${LOOM_TEMPO_OTLP_HTTP_PORT}:${LOOM_TEMPO_OTLP_HTTP_PORT}"
            - "${LOOM_TEMPO_OTLP_GRPC_PORT}:${LOOM_TEMPO_OTLP_GRPC_PORT}"
        command: [ "-config.file=/etc/tempo/tempo.yaml" ]
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    loom-victoria-metrics:
        image: victoriametrics/victoria-metrics:v1.118.0
        container_name: "${LOOM_VICTORIA_METRICS_CONTAINER_NAME}"
        volumes:
            - "../${LOOM_VICTORIA_METRICS_VOLUME_DIR}:/victoria-metrics-data"
        ports:
            - "${LOOM_VICTORIA_METRICS_HTTP_PORT}:${LOOM_VICTORIA_METRICS_HTTP_PORT}"
        command:
            - '-storageDataPath=/victoria-metrics-data'
            - '-retentionPeriod=30d'
            - '-httpListenAddr=:8428'
            - '-memory.allowedPercent=80'
            - '-search.maxUniqueTimeseries=1000000'
            - '-search.maxQueryDuration=120s'
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    loom-weed-master:
        image: chrislusf/seaweedfs
        logging: *default-logging
        container_name: loom-weed-master
        ports:
            - "${LOOM_WEED_MASTER_PORT}:${LOOM_WEED_MASTER_PORT}"
        command: "master"
        networks:
            - net

    loom-weed-volume:
        image: chrislusf/seaweedfs:latest
        container_name: loom-weed-volume
        command: >
            volume 
            -mserver="${LOOM_WEED_MASTER_CONTAINER_NAME}:${LOOM_WEED_MASTER_PORT}" 
            -ip.bind=0.0.0.0 
            -port=8080 
            -dir="/data"
            -max=10
            -metricsPort=9325
            -dataCenter=dc1
            -rack=rack2
        volumes:
            - "../${LOOM_WEED_VOLUME_DIR}:/data"
        depends_on:
            - loom-weed-master
        networks:
            - net
        restart: unless-stopped
        logging: *default-logging

    loom-weed-filer:
        image: chrislusf/seaweedfs:latest
        container_name: loom-weed-filer
        command: >
            filer 
            -master="${LOOM_WEED_MASTER_CONTAINER_NAME}:${LOOM_WEED_MASTER_PORT}"
            -ip.bind=0.0.0.0 
            -metricsPort=9327
        depends_on:
            - loom-weed-master
            - loom-weed-volume
        networks:
            - net
        restart: unless-stopped
        logging: *default-logging